### ISSUE TITLE
Unable to connect to Netbox host

### ISSUE THREAD

**Issue by telecomschik** [jagter/python-netbox#12]
Hi!
I try to connect to Netbox, but it failed! I dont use token or any passwords, becouse i want to GET data only. My script contains this code:
`netbox = NetBox(host='172.24.213.34', port=8000, use_ssl=False)
devices = netbox.dcim.get_devices()`
But:
`Traceback (most recent call last):
  File "C:/Users/vartemenok/PycharmProjects/NETBOX_API_v0.1/main.py", line 6, in <module>
    devices = netbox.dcim.get_devices()
  File "C:\Users\vartemenok\PycharmProjects\NETBOX_API_v0.1\venv\lib\site-packages\netbox\dcim.py", line 95, in get_devices
    return self.netbox_con.get('/dcim/devices/', **kwargs)
  File "C:\Users\vartemenok\PycharmProjects\NETBOX_API_v0.1\venv\lib\site-packages\netbox\connection.py", line 87, in get
    resp_ok, resp_status, resp_data = self.__request('GET', params=param, key=key, url=url)
  File "C:\Users\vartemenok\PycharmProjects\NETBOX_API_v0.1\venv\lib\site-packages\netbox\connection.py", line 62, in __request
    raise ConnectionError(err_msg)
ConnectionError: Unable to connect to Netbox host: 172.24.213.34`
When i use POSTMAN there are no problems.

**Comment by jagter** [comment]
Hi,

Could you tell me which python version you use?

**Comment by telecomschik** [comment]
Hello,
Python 3.7.0 
May be this will help:
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='172.24.213.34', port=8000): Max retries exceeded with url: /api/dcim/devices/?name=bar12er1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x02E6B1D0>: Failed to establish a new connection: [WinError 10057] Запрос на отправку или получение данных  (when sending on a datagram socket using a sendto call) no address was supplied'))`

**Comment by jagter** [comment]
Hi,

Sorry for the late comment. It looks like you're connecting to a wrong port or host. Could you try it with curl and paste the output here. Or paste a screenshot from postman with a working setup.

**Comment by telecomschik** [comment]
Hello,
Thank you for advice. You are right!  I've checked a port that postman use.
Postman used 80 port, but i wrote down 8000 port in my script. I changed
the port and all work fine. =))  Thank you a lot again.

пн, 3 дек. 2018 г. в 22:09, Thomas van der Jagt <notifications@github.com>:
