### ISSUE TITLE
Add support for the `_choices` endpoint

### ISSUE THREAD

**Issue by skoenig** [jagter/python-netbox#17]
Netbox has a [`_choices` endpoint](https://netbox.readthedocs.io/en/latest/api/overview/#static-choice-fields), which is currently not supported by python-netbox. With access to the choices mappings of all assets it would be able to get the name-to-id mapping for e.g. assest status.

**Comment by jagter** [comment]
The _choices endpoint is implemented in the master branch. All the available models have a get_choices method. Please let me know if you are satisfied with the solution.

**Comment by skoenig** [comment]
Looks good, thanks!
