### ISSUE TITLE
unable to create_interface with form_factor=[1000]

### ISSUE THREAD

**Issue by haneyf** [jagter/python-netbox#20]
hi,
thanks for the tool.

I am trying to use the tool to create an interface: and hitting this error:

```
netbox.dcim.create_interface(name='test', device_id='rt01', form_factor=[1000])
[...]
Traceback (most recent call last):
[...]
netbox.exceptions.CreateException: Creation failed with unknown reason
```

I did see netbox code and it looks like Jeremy has renamed form_factor to type, and form_factor will be removed from v2.7: https://github.com/netbox-community/netbox/pull/3067/files

however, even using those codes results in the above error. unsure if this is already being worked upon?

thanks

**Comment by jagter** [comment]
Hi,

Thank you for your input.
I'll take a look at it asap.

**Comment by jagter** [comment]
I replaced the form_factor with interface_type. The code is committed to the master branch.
