### ISSUE TITLE
There are no get_device_by_name()

### ISSUE THREAD

**Issue by za-arthur** [jagter/python-netbox#22]
Hello,

It seems there are no `get_device_by_name()` method anymore. But it is mentioned in the documentation:

https://python-netbox.readthedocs.io/en/latest/examples.html#examples

**Comment by jagter** [comment]
Hello,

Thank you for your email. I have to update the documentation with sphinx 
and upload to readthedocs.

Best Regards,

Thomas

**Comment by jagter** [comment]
The documentation is updated. (README and readthedocs) Please let me know if something is missing

**Comment by za-arthur** [comment]
Everything is okay. Thanks!
