### ISSUE TITLE
Get device multiple roles

### ISSUE THREAD

**Issue by metabsd** [jagter/python-netbox#23]
Hi, I find that is possible to `.dcim.get_devices(role=role, tag=tag)`

How can I query for multiple roles ?

With Netbox UI it's possible via `https://URL/dcim/devices/?q=&role=role1&role=role2`

Thx in advance :)

**Comment by nshenry03** [comment]
🤷‍♂ , could you try this? Or something like it?

```BASH
role1_devices = netbox.dcim.get_devices(role=role1, tag=tag)
role2_devices = netbox.dcim.get_devices(role=role2, tag=tag)
devices = role1_devices + role1_devices
```

**Comment by jagter** [comment]
In the code kwargs is used to parse input parameters. It is not allowed to have duplicate keys in a dictionary. I'm thinking of allowing a list as parameter. 
For example:
`.dcim.get_devices(role=['role1', 'role2'], tag=tag)`

But I'm not sure if this is desirable.

**Comment by metabsd** [comment]
> 🤷‍♂ , could you try this? Or something like it?
> 
> ```shell
> role1_devices = netbox.dcim.get_devices(role=role1, tag=tag)
> role2_devices = netbox.dcim.get_devices(role=role2, tag=tag)
> devices = role1_devices + role1_devices
> ```

That solution works! KISS :)

**Comment by metabsd** [comment]
> In the code kwargs is used to parse input parameters. It is not allowed to have duplicate keys in a dictionary. I'm thinking of allowing a list as parameter.
> For example:
> `.dcim.get_devices(role=['role1', 'role2'], tag=tag)`
> 
> But I'm not sure if this is desirable.

The NetBox API expects to receive a string. The list does not work. It would be necessary to create a function which receives the list and which iterates in the end to make several calls to the API and return the result. Thanks for the idea!

**Comment by jagter** [comment]
> > In the code kwargs is used to parse input parameters. It is not allowed to have duplicate keys in a dictionary. I'm thinking of allowing a list as parameter.
> > For example:
> > `.dcim.get_devices(role=['role1', 'role2'], tag=tag)`
> > But I'm not sure if this is desirable.
> 
> The NetBox API expects to receive a string. The list does not work. It would be necessary to create a function which receives the list and which iterates in the end to make several calls to the API and return the result. Thanks for the idea!

You're right about the API. The idea was to write a function which get the list and extracts the elements and append them to the parameters.
