### ISSUE TITLE
filters don't seem to work

### ISSUE THREAD

**Issue by jaymzh** [jagter/python-netbox#28]
```
x = netbox.dcim.get_devices(name__ic="ro")
```

returns all of my hosts not just hosts containing `ro` in their name. But my understanding based on https://netbox.readthedocs.io/en/stable/api/filtering/ is that that should work...

**Comment by jagter** [comment]
I've tested the filter on the master branch and it works as expected.

`device = a.dcim.get_devices(name__ic='server')

URL:
http://127.0.0.1:32768/api/dcim/devices/?name__ic=compute&limit=0`

**Comment by jaymzh** [comment]
Its probably added in a version more recent of netbox than ours. We're working on upgrading. Will close this. Thanks!
