### ISSUE TITLE
Url print behaivor

### ISSUE THREAD

**Issue by sregister** [jagter/python-netbox#29]
I've noticed that when we hit an API endpoint the corresponding URL is printed.

For example calling:
`netbox.dcim.get_manufacturers() `

will print this to stdout:
`http://<nb_ip>:<np_port>/api/dcim/manufacturers/?limit=0`

For large scripts this can cause a lot of unnecessary output. What are your thoughts on a PR that would would make the default behavior to not print the url unless `netbox.dcim.get_manufacturers(url_debug=True)`

**Comment by jagter** [comment]
Are you using the latest version? The printed URL is only for debug purposes and should not be printed to the output

**Comment by sregister** [comment]
I am using pip3. When I download and extract the tar.gz from [https://pypi.org/project/python-netbox/#files](https://pypi.org/project/python-netbox/#files) I can see the `print(url)` being called as part of `get()` in `connection.py`.

**Comment by jagter** [comment]
Thanks for your report. A new release is available; 0.0.17
