### ISSUE TITLE
No support for netbox running not on the website root (http://.../netbox/)

### ISSUE THREAD

**Issue by kasimon** [jagter/python-netbox#3]
Our netbox runs on https://$server/netbox/, so the api is at .../netbox/api/. This is currently not possible with the way python-netbox constructs its url:

https://github.com/jagter/python-netbox/blob/ada9ae1c7dc0168ce84bf209dbe0aab9b3c3435f/netbox/connection.py#L19

**Comment by jagter** [comment]
Please check the latest commit in master. (05eb0cc)

You can use the api_prefix argument to set the base_url prefix. Are you satisfied with this option?

**Comment by kasimon** [comment]
Yes, that looks good.
