### ISSUE TITLE
get_next_available_ip hard-coded prefix id

### ISSUE THREAD

**Issue by yggdr** [jagter/python-netbox#30]
Just investigating the usefulness of this library, and I found the `ipam.get_next_available_ip`. Looked useful, but in its implementation, it calls `get_ip_prefixes` and always uses the first prefix it finds as the basis. I cannot seem to provide it with filter kwargs that works, since it will always call the underlying `netbox_con.get` method with `param='/ipam/prefixes/' and no way to change that. Any kwargs would just be appended as GET parameters, but if I interpret the netbox API correctly, I would need to change the param to ''/ipam/prefixes/<some ID>'.

Am I overlooking something or it this a bug?

**Comment by jagter** [comment]
Thanks for your issue. I'll investigate the problem and find a solution for this

**Comment by jagter** [comment]
You can find a prefix based on its id. For example:
>>> netbox.ipam.get_next_available_ip(id=1)

This will give you the first free IP address available.
