### ISSUE TITLE
get_ip_prefixes for IP adress provided

### ISSUE THREAD

**Issue by nshrest** [jagter/python-netbox#31]
Hi looking for a option to search ip prefixe based on ipaddress provided ... or is there something  already there ?

eg: 
netbox.ipam.get_ip_prefixes(address='192.168.34/32')

and returns me back relevant prefix for this as
prefix = 192.168.34.0/128

Please help

**Comment by jagter** [comment]
Hi

You can use contains as keyword argument.
eg:
netbox.ipam.get_ip_prefixes(contains='192.168.34.1/32')
