### ISSUE TITLE
update/delete an object by ID

### ISSUE THREAD

**Issue by tdrevvatne** [jagter/python-netbox#32]
Hi
Currently, we have to use "name" as ID to update and delete an object.
Having a lot of objects with names including letters like "+" and "&", we're experiencing issues - like "Unable to find tenant"
Create the same objects with those names are not issues.
Sorry - but considering to search for another libary to overcome such issue...

Will ask for an option to use "ID" as ID for update/delete.

**Comment by jagter** [comment]
Hi,

I'll see what I can do to fix this issue. But feel free to create a PR to improve the quality of this library.
