### ISSUE TITLE
Add support for Custom Fields

### ISSUE THREAD

**Issue by jrbeilke** [jagter/python-netbox#36]
Netbox 2.10 introduced REST API support for managing custom fields:
https://github.com/netbox-community/netbox/issues/5274

Should be able to add this to extras in python-netbox

**Comment by DarylStark** [comment]
This is already possible and I'm using it;

```python
netbox.ipam.create_ip_address(
    address='192.168.26.10',
    custom_fields={
        'my_custom_field': 'my_value'
    }
)
```

**Comment by jagter** [comment]
> This is already possible and I'm using it;
> 
> ```python
> netbox.ipam.create_ip_address(
>     address='192.168.26.10',
>     custom_fields={
>         'my_custom_field': 'my_value'
>     }
> )
> ```

It's already possible.
