### ISSUE TITLE
/dcim/interface-connections endpoint is now read-only

### ISSUE THREAD

**Issue by netdevadm** [jagter/python-netbox#44]
The /dcim/interface-connections endpoint is now read-only. All connections are now created via the /dcim/cables/ endpoint. Marking this as a bug because the endpoint shouldn't accept a POST request at all.
[](https://github.com/netbox-community/netbox/issues/2680#issuecomment-446602293)

**Comment by jagter** [comment]
interface-connections set to read-only.
