### ISSUE TITLE
How to call api/dcim/devices/{id}?

### ISSUE THREAD

**Issue by dajose** [jagter/python-netbox#6]
I am not sure on how to call the api with positional args

**Comment by jagter** [comment]
Hi @dajose 

There is an example in the readme:
`>>> netbox.dcim.get_devices(name='device_name')`

You can check the netbox api docs (swagger) for the argument options. The library uses the same layout.

I hope this helps

**Comment by dajose** [comment]
oh, thx, I though device name was something different to device id
